# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.5'
gem 'rails', '~> 7.0.8', '>= 7.0.8.1'

# TODO: バージョン指定をしていないものはする
gem 'bootsnap', '>= 1.1.0', require: false
gem 'bugsnag'
gem 'bulma-rails'
gem 'chartkick'
gem 'dotenv-rails', '~> 2.7.6'
gem 'gon', '>= 6.3.1'
gem 'mysql2'
gem 'sassc-rails', '~> 2.1.1'
gem 'slim-rails', '>= 3.3.0'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'
gem 'unicorn', '~> 5.5.0'

group :development, :test do
  gem 'awesome_print'
  gem 'better_errors', '>= 2.6.0'
  gem 'binding_of_caller'
  gem 'byebug'
  gem 'factory_bot_rails', '>= 5.0.2'
  gem 'pry-byebug'
  gem 'pry-coolline'
  gem 'pry-doc', '>= 1.1.0'
  gem 'pry-rails'
  gem 'rspec-rails', '>= 3.8.3'
end

group :development do
  gem 'brakeman'
  gem 'capistrano-bundler'
  gem 'capistrano-rails', '~> 1.4.0'
  gem 'capistrano-rails-console', require: false
  gem 'capistrano-rbenv'
  gem 'capistrano-yarn'
  gem 'capistrano3-unicorn'
  gem 'erd', '>= 0.6.4'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rubocop-rails_config', '~> 0.4.4'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 4.0.0'
end

group :test do
  gem 'capybara', '>= 3.15.0'
  gem 'chromedriver-helper', '>= 2.1.1'
  gem 'selenium-webdriver'
end
