source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'rails', '~> 7.0.8', '>= 7.0.8.1'
gem 'sass-rails', '~> 5.0', '>= 5.0.8'
gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 5.0', '>= 5.0.0'
gem 'gon', '>= 6.3.1'
gem 'haml-rails', '>= 2.0.1'
gem 'jbuilder', '~> 2.5'
gem 'webpacker', '>= 4.0.3'

gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'haml-lint'
  gem 'rubocop'
end

group :development do
  gem 'erb2haml'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 4.0.0'
end

group :test do
  gem 'capybara', '>= 3.0.0'
  gem 'chromedriver-helper', '>= 2.1.1'
  gem 'selenium-webdriver'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
