source 'https://rubygems.org'


gem 'rails', '7.0.8.1'

gem 'coffee-rails', '~> 4.2.2'
gem 'jbuilder', '~> 2.0'
gem 'sass-rails', '~> 5.0', '>= 5.0.8'
gem 'sdoc', '~> 1.0.0', group: :doc
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'fuubar'
  gem 'guard-rspec'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'rspec-rails', '>= 3.5.0'
  gem 'spring'
  gem 'terminal-notifier-guard'
  gem 'web-console', '~> 2.3', '>= 2.3.0'
end

