source 'https://rubygems.org'


gem 'rails', '7.1.0'

gem 'coffee-rails', '~> 4.2.2'
gem 'jbuilder', '~> 2.6', '>= 2.6.4'
gem 'sass-rails', '~> 6.0', '>= 6.0.0'
gem 'sdoc', '~> 1.0.0', group: :doc
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'fuubar'
  gem 'guard-rspec', '>= 4.6.4'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'rspec-rails', '>= 3.5.0'
  gem 'spring'
  gem 'terminal-notifier-guard'
  gem 'web-console', '~> 3.0', '>= 3.0.0'
end

