source 'https://rubygems.org'

gem 'rails', '~> 7.0', '>= 7.0.8.1'
# Use Puma as the app server
gem 'puma'
gem 'sqlite3'
# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'rspec-rails', '>= 3.5.0'
  gem 'simplecov'
end

group :development do
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'pry-rails'
end
